version: "3"
services:
  node1:
    build: .
    ports:
      - "7001:7000"
    command: ["python", "node.py", "node1", "node1,node2,node3"]

  node2:
    build: .
    ports:
      - "7002:7000"
    command: ["python", "node.py", "node2", "node1,node2,node3"]

  node3:
    build: .
    ports:
      - "7003:7000"
    command: ["python", "node.py", "node3", "node1,node2,node3"]