services:
  node1:
    build: .
    ports:
      - "5000:5000"
    environment:
      - NODE_ID=node1
      - PEERS=http://node2:5000,http://node3:5000

  node2:
    build: .
    ports:
      - "5001:5000"
    environment:
      - NODE_ID=node2
      - PEERS=http://node1:5000,http://node3:5000

  node3:
    build: .
    ports:
      - "5002:5000"
    environment:
      - NODE_ID=node3
      - PEERS=http://node1:5000,http://node2:5000
